=== CarloMicieli/Trenako/crates/cli/src/schemas/catalog-items.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CatalogItem",
  "type": "object",
  "required": [
    "brand",
    "item_number",
    "scale",
    "category",
    "description",
    "count"
  ],
  "properties": {
    "brand": {
      "type": "string"
    },
    "item_number": {
      "type": "string"
    },
    "scale": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": [
        "ELECTRIC_MULTIPLE_UNITS",
        "FREIGHT_CARS",
        "LOCOMOTIVES",
        "PASSENGER_CARS",
        "RAILCARS",
        "STARTER_SETS",
        "TRAIN_SETS"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "power_method": {
      "type": "string",
      "enum": [
        "AC",
        "DC",
        "TRIX_EXPRESS"
      ]
    },
    "delivery_date": {
      "type": [
        "string",
        "null"
      ]
    },
    "availability_status": {
      "type": "string",
      "enum": [
        "ANNOUNCED",
        "AVAILABLE",
        "DISCONTINUED"
      ]
    },
    "rolling_stocks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RollingStock"
      }
    },
    "count": {
      "type": "integer",
      "format": "uint8",
      "minimum": 0.0
    }
  },
  "definitions": {
    "RollingStock": {
      "type": "object",
      "required": [
        "epoch",
        "railway",
        "technical_specifications"
      ],
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "ELECTRIC_MULTIPLE_UNIT",
            "FREIGHT_CAR",
            "LOCOMOTIVE",
            "PASSENGER_CAR",
            "RAILCAR"
          ]
        },
        "control": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "DCC",
            "DCC_READY",
            "DCC_SOUND",
            "NO_DCC"
          ]
        },
        "dcc_interface": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "MTC_21",
            "NEM_651",
            "NEM_652",
            "NEM_654",
            "NEXT_18",
            "NEXT_18_S",
            "PLUX_12",
            "PLUX_16",
            "PLUX_22",
            "PLUX_8"
          ]
        },
        "depot": {
          "type": [
            "string",
            "null"
          ]
        },
        "dummy": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "epoch": {
          "type": "string"
        },
        "length": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint32",
          "minimum": 0.0
        },
        "livery": {
          "type": [
            "string",
            "null"
          ]
        },
        "railway": {
          "type": "string"
        },
        "road_number": {
          "type": [
            "string",
            "null"
          ]
        },
        "series": {
          "type": [
            "string",
            "null"
          ]
        },
        "service_level": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "FIRST_CLASS",
            "SECOND_CLASS",
            "FIRST_AND_SECOND_CLASS",
            "FIRST_SECOND_AND_THIRD_CLASS",
            "SECOND_AND_THIRD_CLASS"
          ]
        },
        "sub_category": {
          "type": [
            "string",
            "null"
          ]
        },
        "technical_specifications": {
          "$ref": "#/definitions/TechSpecs"
        },
        "type_name": {
          "type": "string"
        }
      }
    },
    "TechSpecs": {
      "type": "object",
      "required": [
        "coupling",
        "flywheel_fitted",
        "interior_lights",
        "lights",
        "metal_body",
        "minimum_radius",
        "spring_buffers"
      ],
      "properties": {
        "coupling": {
          "$ref": "#/definitions/Coupling"
        },
        "flywheel_fitted": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "interior_lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "metal_body": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "minimum_radius": {
          "type": "number"
        },
        "spring_buffers": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    },
    "Coupling": {
      "type": "object",
      "properties": {
        "socket": {
          "type": ["string", "null"],
          "enum": [
            "NONE",
            "NEM_355",
            "NEM_356",
            "NEM_357",
            "NEM_359",
            "NEM_360",
            "NEM_362",
            "NEM_365"
          ]
        },
        "close_couplers": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "digital_shunting": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    },
    "FeatureFlag": {
      "type": "string",
      "enum": [
        "YES",
        "NO",
        "NOT_AVAILABLE"
      ]
    }
  }
}

=== CarloMicieli/Trenako/dataset/catalog_items/acme/locomotives/69440.json
{
  "brand" : "ACME",
  "item_number" : "69440",
  "category" : "LOCOMOTIVES",
  "scale" : "H0",
  "power_method" : "DC",
  "description" : {
    "it" : "Locomotive elettrica FS E636 351 XMPR Trenitalia prima versione, luci rosse, terzo faro alto, aria condizata, OMR La Spezia",
    "en" : null
  },
  "details" : {
    "it" : null,
    "en" : null
  },
  "delivery_date" : "2014",
  "availability_status" : "AVAILABLE",
  "count" : 1,
  "rolling_stocks" : [ {
    "category" : "LOCOMOTIVE",
    "class_name" : "E636",
    "road_number" : "E636 351",
    "series" : "TERZA SERIE",
    "locomotive_type" : "ELECTRIC_LOCOMOTIVE",
    "railway" : "FS",
    "epoch" : "Vb",
    "livery" : "XMPR",
    "depot" : "La Spezia",
    "dcc_interface" : "MTC_21",
    "control" : "DCC_SOUND",
    "length_over_buffer" : {
      "inches" : null,
      "millimeters" : 210.0
    },
    "technical_specifications" : {
      "minimum_radius" : 360.0,
      "coupling" : {
        "socket" : "NEM_362",
        "close_couplers" : "YES",
        "digital_shunting" : "NO"
      },
      "flywheel_fitted" : "NO",
      "metal_body" : "NO",
      "interior_lights" : "NO",
      "lights" : "YES",
      "spring_buffers" : "NO"
    },
    "is_dummy" : false
  } ]
}

=== CarloMicieli/Trenako/dataset/catalog_items/acme/locomotives/69128.json
{
  "brand" : "ACME",
  "item_number" : "69128",
  "scale" : "H0",
  "category" : "LOCOMOTIVES",
  "description" : {
    "values" : {
      "it" : "Locomotiva elettrica 646 ??? in livrea verde/grigio con modanature, prese di aria modificate, scalette grandi (69128 DCC Sound)",
      "en" : null
    }
  },
  "details" : {
    "values" : {
      "it" : null,
      "en" : null
    }
  },
  "power_method" : "DC",
  "delivery_date" : "2023",
  "availability_status" : "ANNOUNCED",
  "rolling_stocks" : [ {
    "category" : "LOCOMOTIVE",
    "class_name" : "E646",
    "road_number" : "E646 ???",
    "series" : "SECONDA SERIE",
    "locomotive_type" : "ELECTRIC_LOCOMOTIVE",
    "railway" : "FS",
    "epoch" : "IV",
    "depot" : "",
    "dcc_interface" : "MTC_21",
    "control" : "DCC_SOUND",
    "livery" : "grigio perla/verde magnolia",
    "length_over_buffer" : {
      "inches" : null,
      "millimeters" : 210.0
    },
    "technical_specifications" : {
      "minimum_radius" : 360.0,
      "coupling" : {
        "socket" : "NEM_362",
        "close_couplers" : "YES",
        "digital_shunting" : "NO"
      },
      "flywheel_fitted" : "NO",
      "metal_body" : "NO",
      "interior_lights" : "NO",
      "lights" : "YES",
      "spring_buffers" : "NO"
    },
    "dummy" : false
  } ],
  "count" : 1
}

=== CarloMicieli/Trenako/dataset/catalog_items/acme/locomotives/60394.json
{
  "brand" : "ACME",
  "item_number" : "60394",
  "scale" : "H0",
  "category" : "LOCOMOTIVES",
  "description" : {
    "values" : {
      "it" : "Locomotiva elettrica FS E656 541 \"Caimano\" (6a serie) nella livrea blu/grigio, smorzatori, striscianti curvi, dep. Napoli Sm.",
      "en" : null
    }
  },
  "details" : {
    "values" : {
      "it" : null,
      "en" : null
    }
  },
  "power_method" : "DC",
  "delivery_date" : "2022",
  "availability_status" : "AVAILABLE",
  "rolling_stocks" : [ {
    "category" : "LOCOMOTIVE",
    "class_name" : "E656",
    "road_number" : "E656 541",
    "series" : "SESTA SERIE",
    "locomotive_type" : "ELECTRIC_LOCOMOTIVE",
    "railway" : "FS",
    "epoch" : "V",
    "depot" : "Napoli Smistamento",
    "dcc_interface" : "MTC_21",
    "control" : "DCC_READY",
    "livery" : "blu/grigio",
    "length_over_buffer" : {
      "inches" : null,
      "millimeters" : 210.0
    },
    "technical_specifications" : {
      "minimum_radius" : 360.0,
      "coupling" : {
        "socket" : "NEM_362",
        "close_couplers" : "YES",
        "digital_shunting" : "NO"
      },
      "flywheel_fitted" : "NO",
      "metal_body" : "NO",
      "interior_lights" : "NO",
      "lights" : "YES",
      "spring_buffers" : "NO"
    },
    "dummy" : false
  } ],
  "count" : 1
}

=== CarloMicieli/Trenako/dataset/catalog_items/acme/locomotives/60321.json
{
  "brand" : "ACME",
  "item_number" : "60321",
  "scale" : "H0",
  "category" : "LOCOMOTIVES",
  "description" : {
    "values" : {
      "it" : "Locomotiva elettrica FS E424 036 nella livrea castano/isabella, porte frontali, separatore D'Arbela, scalette strette",
      "en" : null
    }
  },
  "details" : {
    "values" : {
      "it" : null,
      "en" : null
    }
  },
  "power_method" : "DC",
  "delivery_date" : "2014",
  "availability_status" : "AVAILABLE",
  "rolling_stocks" : [ {
    "category" : "LOCOMOTIVE",
    "class_name" : "E424",
    "road_number" : "E424 036",
    "series" : "",
    "locomotive_type" : "ELECTRIC_LOCOMOTIVE",
    "railway" : "FS",
    "epoch" : "IIIb",
    "depot" : "",
    "dcc_interface" : "MTC_21",
    "control" : "DCC_READY",
    "livery" : "castano/isabella",
    "length_over_buffer" : {
      "inches" : null,
      "millimeters" : 178.0
    },
    "technical_specifications" : {
      "minimum_radius" : 360.0,
      "coupling" : {
        "socket" : "NEM_362",
        "close_couplers" : "YES",
        "digital_shunting" : "NO"
      },
      "flywheel_fitted" : "NO",
      "metal_body" : "NO",
      "interior_lights" : "NO",
      "lights" : "YES",
      "spring_buffers" : "NO"
    },
    "dummy" : false
  } ],
  "count" : 1
}

=== CarloMicieli/Trenako/dataset/catalog_items/acme/locomotives/69162.json
{
  "brand" : "ACME",
  "item_number" : "69162",
  "category" : "LOCOMOTIVES",
  "scale" : "H0",
  "power_method" : "DC",
  "description" : {
    "it" : "Locomotiva elettrica FS E646 062 nella livrea verde/grigio, modanature, scalette larghe, prese aria origine, vomere nero",
    "en" : null
  },
  "details" : {
    "it" : "Locomotiva elettrica E 646 062 nella livrea verde magnolia grigio nebbia, con scalette larghe e tientibene lunghi; unica ad aver mantenuto la configurazione delle prese d'aria originali su entrambi i lati sino alla trasformazione in navetta dei primi anni 80'. Edizione limitata",
    "en" : null
  },
  "delivery_date" : "2018",
  "availability_status" : "AVAILABLE",
  "count" : 1,
  "rolling_stocks" : [ {
    "category" : "LOCOMOTIVE",
    "class_name" : "E646",
    "road_number" : "E646 062",
    "series" : "SECONDA SERIE",
    "locomotive_type" : "ELECTRIC_LOCOMOTIVE",
    "railway" : "FS",
    "epoch" : "IVa",
    "livery" : "verde/grigio",
    "depot" : null,
    "dcc_interface" : "MTC_21",
    "control" : "DCC_SOUND",
    "length_over_buffer" : {
      "inches" : null,
      "millimeters" : 210.0
    },
    "technical_specifications" : {
      "minimum_radius" : 360.0,
      "coupling" : {
        "socket" : "NEM_362",
        "close_couplers" : "NO",
        "digital_shunting" : "NO"
      },
      "flywheel_fitted" : "NO",
      "metal_body" : "NO",
      "interior_lights" : "NO",
      "lights" : "YES",
      "spring_buffers" : "NO"
    },
    "is_dummy" : false
  } ]
}
